### ISSUE TITLE
Received unexpected status code 400

### ISSUE THREAD

**Issue by wavemoroc001** [virtualzone/onedrive-uploader#8]
I have tried to upload file to one drive but it throw  `Could not upload file: received unexpected status code 400`

How can i fix this error ?
@virtualzone

**Comment by virtualzone** [comment]
Hi @wavemoroc001, can you provide a bit more information?

* Are you logged in?
* Does listing files work?
* Does creating directories work?
* Does the error only happen with specific files (i.e. size, file type) or with all the files you've tried?

**Comment by wavemoroc001** [comment]
@virtualzone 
1. Are you logged in?
I don't sure is my login is successfully ?? (as my screenshot)
but on console log login successful and got secret.json file

![Screen Shot 2565-09-18 at 01 07 28](https://user-images.githubusercontent.com/56395197/190870661-77fd8427-4e06-4b7a-8cc9-53af7d28bc17.png)

2. Does listing files work?
No, it also throw same error `Could not list: received unexpected status code 400`

4. Does creating directories work?
Nope it throw error `Could not list: received unexpected status code 400`

6. Does the error only happen with specific files (i.e. size, file type) or with all the files you've tried?
In my case, I try to upload image (jpg) that size is less than 1 MB and it blow up with status 400

**Comment by virtualzone** [comment]
@wavemoroc001 Thanks for your response. I've just released version 0.4.5 which includes an improved error handling (especially more verbose error messages).

Could you try again with v0.4.5 and post the output? Please also run with the "-v" (verbose) flag.

**Comment by wavemoroc001** [comment]
@virtualzone 
I upgrade to version 0.4.5 and still get error.
This is my log

<img width="1027" alt="Screen Shot 2565-09-19 at 00 35 16" src="https://user-images.githubusercontent.com/56395197/190920762-38539228-131e-4fca-9e92-7221889b4b78.png">

### For more detail
config in app registration
![Screen Shot 2565-09-18 at 22 37 10](https://user-images.githubusercontent.com/56395197/190921582-b7047291-9f78-4197-ab2e-8c0620e18e82.png)

`config.json`
![Screen Shot 2565-09-19 at 00 53 31](https://user-images.githubusercontent.com/56395197/190921629-b06b6c3d-ed66-45a9-8673-32c98fd46a95.png)

**Comment by virtualzone** [comment]
Hi @wavemoroc001 ,

please review your "root" path setting in the config.json. It sets the root path *within* your OneDrive, not your local drive. Thus, it should usually be set to "/drive/root". 

Secondly, please use "/" instead of "." when specifying paths in your OneDrive. So, instead of "ls ." use "ls /" (which is relative to the specified root path, see above).

Please check the README for more information.

**Comment by wavemoroc001** [comment]
Hi @virtualzone 
I tried follow your advices but it still get status 400 

following this configuration 

This is step i use app

<img width="1040" alt="Screen Shot 2565-09-23 at 11 34 37" src="https://user-images.githubusercontent.com/56395197/191892997-60993ea5-f3f1-4e69-8193-7ae47fd262c2.png">

config.json

<img width="626" alt="Screen Shot 2565-09-23 at 11 36 38" src="https://user-images.githubusercontent.com/56395197/191893042-d97e2b8b-d6e8-4878-84cc-f71b7b382588.png">

This is root dir  which i have mapped

![Screen Shot 2565-09-23 at 11 33 52](https://user-images.githubusercontent.com/56395197/191893100-9162576b-fe26-44f2-8459-1018097ed1e5.png)

**Comment by virtualzone** [comment]
Hi @wavemoroc001,
I hope to have fixed the Dynamic Path Segment Error in Version 0.4.7. Could you try the new version?
However, your "root" path setting is still incorrect. Please use "/drive/root" (nothing to replace here - just copy & paste).

**Comment by wavemoroc001** [comment]
@virtualzone 

Oh, thank you so much 
I have try till it work.

<img width="845" alt="Screen Shot 2565-09-25 at 01 40 08" src="https://user-images.githubusercontent.com/56395197/192113703-6332adf3-384c-4b31-9e19-cbf7f29a1dbf.png">

**Comment by wavemoroc001** [comment]
@virtualzone Cloud you improve ui screen eg. add estimate time or progress bar ? when i upload large file it look like it freezing

**Comment by virtualzone** [comment]
@wavemoroc001 I'm glad it's working now. Thanks for your idea on adding a progress bar/estimated time remaining. I've created a new issue for that (see above).
